@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Calculation of Execution Times by Each Operation

autonumber

actor "Product Manager" as ProductManager
participant ":System" as System

activate ProductManager

    ProductManager -> System : Requests execution time for each operation
    activate System

        System -> System : Calculate execution time per operation
        System --> ProductManager : Returns execution times for each operation

    deactivate System
deactivate ProductManager

@enduml
