@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - USEI19: Topological Sort of Project Activities

class ProjectManager {
    name
    email
    role
    performTopologicalSort()
}

class PERTCPMGraph {
    id
    activities
    dependencies
    performTopologicalSort()
}

ProjectManager "1" - "1" PERTCPMGraph : requests >
PERTCPMGraph "1" - "*" Activity : contains >
Activity "1" - "*" Activity : depends on >

@enduml
