@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Build Production Tree

autonumber

actor "Production Manager" as ProductionManager
participant ":System" as System

activate ProductionManager

    ProductionManager -> System : Request to build the production tree
    activate System

        System -> System : Import data from CSV (operations, components, materials)
        System -> System : Create the production tree structure
        System -> System : Validate and link subcomponents and materials
        System -> System : Store production tree in memory

        System --> ProductionManager : Returns production tree successfully built

    deactivate System
deactivate ProductionManager

@enduml
