@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - Display Average Execution and Waiting Times for Operations

class SystemUser {
    name
    email
    role
}

class Article {
    id
    priority
    operations
}

class Operation {
    id
    name
    executionTime
    waitingTime
}

class Workstation {
    id
    operation
    executionTime
    waitingTime
}



class ProductManager {
    name
    email
    password
    role
    phone: String
    createSimulation
    manageUsers
    viewReports
    }

class ExecutionTime {
    value
}

class WaitingTime {
    value
}

SystemUser <|-- ProductManager


ProductManager "1" -- "1..*" Article : manages >
ProductManager "1" -- "1..*" Workstation : oversees >

Workstation "1" -- "0..*" Operation : performs >
Operation "1" -- "1" ExecutionTime : has >
Operation "1" -- "1" WaitingTime : has >

@enduml
