@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - USEI07: Flow Dependency Between Workstations

class Simulator {
        fromWorkstation
        toWorkstation
        itemsProcessed
}


class ProductManager {
    name
    email
    password
    role
    phone: String
    createSimulation
    manageUsers
    viewReports
    }

class Workstation {
    id : int
    name : String
    processedItemsCount : int
    nextWorkstation : Workstation
}

class Operation {
    name : String
    time : int
    workstation : Workstation
}



class Item {
    id : int
    priority : String
    operations : List<Operation>
}

ProductManager "1" - "1" Simulator : requests data from >
Simulator "1" - "*" Workstation : uses >
Workstation "1" - "*" Operation : performs >
Item "1" - "*" Operation : consists of >

@enduml
