@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Flow Dependency Between Workstations

autonumber

actor "Product Manager" as ProductManager
participant ":System" as System

activate ProductManager

    ProductManager -> System : Requests flow dependency between workstations
    activate System

        System -> System : Analyze items processed by each workstation
        System -> System : Generate flow dependencies and sort by processed items count

        System --> ProductManager : Returns sorted flow dependency list

    deactivate System
deactivate ProductManager

@enduml
