@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - Calculate Total Quantities and Time

class ProductionManager {
    name
    email
    password
    role
    phone: String
    calculateTotalQuantitiesAndTime
}

class ProductionTree {
    id
    itemName
    operations
    materials
    calculateTotalQuantities
    calculateTotalTime
}

class Material {
    id
    name
    quantity
}

class Operation {
    id
    name
    averageTime
}

ProductionManager "1" - "1" ProductionTree : calculates for >
ProductionTree "1" - "*" Material : contains >
ProductionTree "1" - "*" Operation : involves >
@enduml
