@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Display Average Execution and Waiting Times for Operations

autonumber

actor "Product Manager" as ProductManager
participant ":System" as System

activate ProductManager

    ProductManager -> System : Requests average execution times per operation and waiting times
    activate System

        System -> System : Process execution and waiting times data

        System --> ProductManager : Returns average execution times and waiting times
    deactivate System

deactivate ProductManager

@enduml
