@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Calculation of Total Production Time for Items

autonumber

actor "Product Manager" as ProductManager
participant ":System" as System

activate ProductManager

    ProductManager -> System : Requests total production time of all items
    activate System
        System -> System : Calculate the total production time for the items


        System --> ProductManager : Returns total production time
    deactivate System

@enduml
