@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - Prioritize Quality Checks

class ProductionManager {
    name
    email
    password
    role
    phone: String
    prioritizeQualityChecks
}

class QualityCheckQueue {
    heap: List<QualityCheck>
    addCheck
    retrieveNextCheck
}

class QualityCheck {
    id
    name
    priority
    stage
}

ProductionManager "1" - "1" QualityCheckQueue : prioritizes using >
QualityCheckQueue "1" - "*" QualityCheck : contains >
@enduml
