@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - Calculation of Total Production Time for Items

class ProductManager {
    name
    email
    password
    role
    phone: String
    createSimulation
    manageUsers
    viewReports
    }

class Simulator {
    currentTime
    calculateTotalProductionTime
}

class Item {
    id
    priority
    operations
    totalProductionTime
}

class Operation {
    name
    time
    workstation
}

class Workstation {
    id
    name
    operationTime
}

ProductManager "1" - "1" Simulator : asks for >
Simulator "1" - "*" Item : calculates >
Item "1" - "*" Operation : requires >
Operation "1" - "1" Workstation : performed by >

@enduml
