@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Put Components into Production in the Simulator

autonumber

actor "Production Manager" as ProductionManager
participant ":System" as System

activate ProductionManager

    ProductionManager -> System : Request to simulate production of components
    activate System

        System -> System : Extract BOO from Production Tree
        System -> System : Build AVL tree for production hierarchy
        System -> System : Traverse AVL tree to schedule components for production
        System -> System : Simulate production for each component

        System --> ProductionManager : Returns simulation results

    deactivate System
deactivate ProductionManager

@enduml
